### **Задание на повторение материала

In [2]:
import numpy as np

Task_1 
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [17]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Task_2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [19]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [24]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [25]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Task_3
Создать 5 двумерных массивов разной формы из массива a.
Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [30]:
a.reshape(2, -1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [32]:
a.reshape(-1, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [33]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

Task_4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [40]:
a_tmp = a.reshape(-1, 1)
a_tmp

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [43]:
a_tmp.ndim

2

In [44]:
Нет, это двумерный массив

Task_5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [53]:
a = np.random.randn(3, 4)
a

array([[ 0.10610936,  0.34303051, -0.85282681, -0.08941609],
       [ 0.25401281, -0.13238848, -0.44569669,  0.76026678],
       [-0.99271689,  0.63239139, -0.72608965, -0.12927344]])

In [56]:
a.size

12

In [64]:
a.flatten()

array([ 0.10610936,  0.34303051, -0.85282681, -0.08941609,  0.25401281,
       -0.13238848, -0.44569669,  0.76026678, -0.99271689,  0.63239139,
       -0.72608965, -0.12927344])

In [66]:
a.size

12

Task_6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [71]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Task_7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
В чем разница между массивами a и b?

In [81]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [82]:
a.ndim

1

In [84]:
b.ndim

2

массив и двумерный

Task_8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [110]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

In [112]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [114]:
v.size

10

Task_9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
Получить матрицу At путем транспонирования матрицы A. 
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [124]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [132]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [136]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [138]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [141]:
B.shape

(4, 4)

In [144]:
d = np.linalg.det(B)
d

0.0

Определитель матрицы = 0, вычислить обратную матрицу не получится

Task_10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [154]:
np.random.seed(42)
np.random.randint(0, 10, 3)

array([6, 3, 7])

Task_11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел
от 0 до 16 невключительно. 

In [158]:
c = np.random.randint(1, 16, 16)
c

array([ 2,  8, 12, 14,  6,  2, 12,  5,  1, 12, 10,  6, 13, 12,  9,  1])

Task_12
Поменяйте его форму так, чтобы получилась квадратная матрица C. 
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [166]:
C = c.reshape((4, -1))
C

array([[ 2,  8, 12, 14],
       [ 6,  2, 12,  5],
       [ 1, 12, 10,  6],
       [13, 12,  9,  1]])

In [171]:
D = (B + C) * 10
D

array([[  70,  220,  350,  460],
       [ 200,  520,  980, 1270],
       [ 240,  980, 1590, 2180],
       [ 450, 1340, 2210, 3030]])

In [175]:
Dt = np.linalg.det(D)
Dt

-375319999.9999988

In [178]:
rung = np.linalg.matrix_rank(D)
rung

4

In [180]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00688479, -0.00186508, -0.01205371,  0.00840882],
       [ 0.03630768, -0.00979697, -0.00060215, -0.0009725 ],
       [ 0.02670255,  0.01141959,  0.00208888, -0.01034317],
       [-0.03655547, -0.00371949,  0.00053288,  0.00705531]])

In [182]:
print(D.dot(D_inv))

[[ 1.00000000e+00  2.22044605e-16 -1.11022302e-16  0.00000000e+00]
 [ 7.10542736e-15  1.00000000e+00 -3.33066907e-16  0.00000000e+00]
 [ 0.00000000e+00  3.55271368e-15  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Task_13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались
только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [185]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 1., 0.],
       [0., 0., 1., 1.]])

In [187]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [188]:
C

array([[ 2,  8, 12, 14],
       [ 6,  2, 12,  5],
       [ 1, 12, 10,  6],
       [13, 12,  9,  1]])

In [189]:
E = np.where(D_inv, B, C)
E

array([[  5,   8,  12,  32],
       [ 14,   2,  12,   5],
       [ 23,  86, 149,   6],
       [ 13,  12, 212, 302]])